version: '3.1'

services:
  broker:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker
    container_name: broker
    ports:
      - "29092:29092"
    environment:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLIENT:PLAINTEXT'
      KAFKA_LISTENERS: 'EXTERNAL://:29092,CONTROLLER://kafka-kraft:29093,CLIENT://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:29092,CLIENT://broker:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'CLIENT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-kraft:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  cli:
    image: confluentinc/cp-kafka:7.4.0
    hostname: cli
    container_name: cli
    depends_on:
      - broker
    entrypoint: /bin/bash
    tty: true
  gui:
    image: obsidiandynamics/kafdrop:3.31.0
    hostname: gui
    container_name: gui
    depends_on:
      - broker
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"

